# random_choose->True
# window_size->50
# 收敛得非常快，50多epoch的时候就能到百分百了
work_dir: ./work_dir/nmv/4-1

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 50
  data_path: ./data/nmv/train_data.npy
  label_path: ./data/nmv/train_label.pkl
test_feeder_args:
  data_path: ./data/nmv/val_data.npy
  label_path: ./data/nmv/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 5
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
phase: train
device: [0]
batch_size: 68
test_batch_size: 68

#optim
base_lr: 0.1
step: [50, 100, 150, 200]
num_epoch: 250

# evaluation
show_topk: [1]

# log
log_interval: 2
