work_dir: ./work_dir/hrnet

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_shift: False
  random_move: True
  data_path: ./data/hrnet/train_data.npy
  label_path: ./data/hrnet/train_label.pkl
test_feeder_args:
  data_path: ./data/hrnet/val_data.npy
  label_path: ./data/hrnet/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 2
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
phase: train
device: [0]
batch_size: 64
test_batch_size: 64

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50

# evaluation
show_topk: [1]
