work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN_TWO_STREAM/default

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150 
  data_path: ./data/Kinetics/kinetics-skeleton/train_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/train_label.pkl
test_feeder_args:
  data_path: ./data/Kinetics/kinetics-skeleton/val_data.npy
  label_path: ./data/Kinetics/kinetics-skeleton/val_label.pkl

# model
model: net.st_gcn_twostream.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
#   dropout: 0.5
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# # training
# device: [0,1,2,3]
# batch_size: 256 
# test_batch_size: 256

# training
device: [0,1]
batch_size: 72
test_batch_size: 72

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 60



